export { api, ApiError, getApiErrorMessage } from "./client";
export { documentsApi } from "./documents";
export { versionsApi } from "./versions";
export { nodesApi } from "./nodes";
export { workflowApi } from "./workflow";
export { searchApi } from "./search";
export { diffApi } from "./diff";
export { ragApi, queryStream } from "./rag";
export { proposalsApi } from "./proposals";
export type { AgentProposal, ProposalListResponse, ProposalStats } from "./proposals";
